//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Zxxk.Gkbb.Model
{

	/// <summary>
	/// 实体类TestTable 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("TestTable")]
	[Serializable]
	public partial class TestTable : Entity 
	{
		#region Model
		private int _TestId;
		private string _Name;
		/// <summary>
		/// 测试ID
		/// </summary>
		public int TestId
		{
			get{ return _TestId; }
			set
			{
				this.OnPropertyValueChange(_.TestId,_TestId,value);
				this._TestId=value;
			}
		}
		/// <summary>
		/// 测试名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.TestId;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TestId,
				_.Name};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TestId,
				this._Name};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TestTable");
			/// <summary>
			/// 测试ID
			/// </summary>
			public readonly static Field TestId = new Field("TestId","TestTable","测试ID");
			/// <summary>
			/// 测试名称
			/// </summary>
			public readonly static Field Name = new Field("Name","TestTable","测试名称");
		}
		#endregion


	}
}

